# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeRig < Formula
  desc "Run multiple Claude Code configurations side by side"
  homepage "https://github.com/edimuj/claude-rig"
  version "0.20.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/edimuj/claude-rig/releases/download/v0.20.0/claude-rig_darwin_amd64.tar.gz"
      sha256 "ad20093d3f62b9ab452df2185e51f6a45b4b5b8e1363c8ecdc46eba326c1625d"

      define_method(:install) do
        bin.install "claude-rig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/edimuj/claude-rig/releases/download/v0.20.0/claude-rig_darwin_arm64.tar.gz"
      sha256 "5db48a3fe75bde686ea58831cabfea6791601a5e3a75768116602f4f6e4c6952"

      define_method(:install) do
        bin.install "claude-rig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/edimuj/claude-rig/releases/download/v0.20.0/claude-rig_linux_amd64.tar.gz"
      sha256 "ce2ce875496d531f2680fefd980e6e82f6c502903de1efb16789bae18f66e9fc"
      define_method(:install) do
        bin.install "claude-rig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/edimuj/claude-rig/releases/download/v0.20.0/claude-rig_linux_arm64.tar.gz"
      sha256 "acad6198150dee7c1d1776f230f457e56b0798a29267ad7d9097d57be84ec5cd"
      define_method(:install) do
        bin.install "claude-rig"
      end
    end
  end

  test do
    system "#{bin}/claude-rig", "version"
  end
end
