# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeRig < Formula
  desc "Run multiple Claude Code configurations side by side"
  homepage "https://github.com/edimuj/claude-rig"
  version "0.29.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/edimuj/claude-rig/releases/download/v0.29.0/claude-rig_darwin_amd64.tar.gz"
      sha256 "9590950555cbeb9fd0773a3c8136a1c359e45580ebc92c8b2044098de367e785"

      define_method(:install) do
        bin.install "claude-rig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/edimuj/claude-rig/releases/download/v0.29.0/claude-rig_darwin_arm64.tar.gz"
      sha256 "568c76f5ffb9dd70c89090b632955f934ff55a01742aaae7ea1f62b924f37b18"

      define_method(:install) do
        bin.install "claude-rig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/edimuj/claude-rig/releases/download/v0.29.0/claude-rig_linux_amd64.tar.gz"
      sha256 "c3584025b565ca3a3ee92ac8cfbd79513cd50fc03d5d4d622ec47a7bb27500e9"
      define_method(:install) do
        bin.install "claude-rig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/edimuj/claude-rig/releases/download/v0.29.0/claude-rig_linux_arm64.tar.gz"
      sha256 "b5437cd6e5a66c9068d34f18140f118f30e35d6a5fc66497032aae39ef015701"
      define_method(:install) do
        bin.install "claude-rig"
      end
    end
  end

  test do
    system "#{bin}/claude-rig", "version"
  end
end
