# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeRig < Formula
  desc "Run multiple Claude Code configurations side by side"
  homepage "https://github.com/edimuj/claude-rig"
  version "0.30.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/edimuj/claude-rig/releases/download/v0.30.0/claude-rig_darwin_amd64.tar.gz"
      sha256 "8e1eac2db3d9719d3414b4accf8faf975ddb2da53349b5d045f10f849789f15a"

      define_method(:install) do
        bin.install "claude-rig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/edimuj/claude-rig/releases/download/v0.30.0/claude-rig_darwin_arm64.tar.gz"
      sha256 "3e3ee889b58a5781329c81ad6fba74a246b0011d04942430c4573ae7cdc5a5a6"

      define_method(:install) do
        bin.install "claude-rig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/edimuj/claude-rig/releases/download/v0.30.0/claude-rig_linux_amd64.tar.gz"
      sha256 "e4ae6a1b2222b7fdc54e39ff5f7d362960d9eae389e863f1ab008ce279290c79"
      define_method(:install) do
        bin.install "claude-rig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/edimuj/claude-rig/releases/download/v0.30.0/claude-rig_linux_arm64.tar.gz"
      sha256 "18fd6c4d5dd3c73ebb2c8ce1f6ef8ff4133cfe127d15bf9e50aafa6790c58a15"
      define_method(:install) do
        bin.install "claude-rig"
      end
    end
  end

  test do
    system "#{bin}/claude-rig", "version"
  end
end
